no downtime2

diff --git a/0x1A-application_server/4-reload_gunicorn_no_downtime b/0x1A-application_server/4-reload_gunicorn_no_downtime
--- a/0x1A-application_server/4-reload_gunicorn_no_downtime
+++ b/0x1A-application_server/4-reload_gunicorn_no_downtime
@@ -1,5 +1,23 @@
 #!/usr/bin/env bash
 # To reload Gunicorn in a graceful way
 
-pgrep gunicorn | xargs kill -HUP
-sudo service gunicorn restart
+# Get the PIDs of Gunicorn processes
+gunicorn_pids=$(pgrep gunicorn)
+
+# Check if Gunicorn processes are running
+if [ -z "$gunicorn_pids" ]; then
+    echo "No Gunicorn processes found."
+    exit 1
+fi
+
+# Send HUP signal to each Gunicorn process
+for pid in $gunicorn_pids; do
+    if kill -HUP "$pid"; then
+        echo "Sent HUP signal to Gunicorn process $pid."
+    else
+        echo "Failed to send HUP signal to Gunicorn process $pid."
+    fi
+done
+
+exit 0
+
